/* ds4_console.h -- the accretion web console page, embedded.
 *
 * Single self-contained HTML page (inline CSS/JS, no external assets, no
 * build step) served by ds4_server.c at GET / and /console.  The page is
 * split in two halves; send_console() renders the server-side STATUS facts
 * (model, quantization, honest-context pair) between them so STATUS and
 * CONNECT are correct even with JavaScript disabled.  JS adds the live
 * ACTIVITY view (polls /v1/activity every 2.5s) and fills <host> from
 * window.location in the CONNECT snippets. */
#ifndef DS4_CONSOLE_H
#define DS4_CONSOLE_H

static const char ds4_console_html_head[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>ds4 console</title>\n"
    "<style>\n"
    ":root{--bg:#0d1117;--panel:#161b22;--line:#30363d;--fg:#e6edf3;--dim:#8b949e;--acc:#58a6ff;--ok:#3fb950;--warm:#d29922}\n"
    "*{box-sizing:border-box;margin:0}\n"
    "body{background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif;max-width:860px;margin:0 auto;padding:1.5rem 1rem}\n"
    "h1{font-size:1.3rem;margin-bottom:.25rem}\n"
    "h1 small{color:var(--dim);font-weight:400;font-size:.8rem;margin-left:.5rem}\n"
    "section{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:1rem;margin-top:1rem}\n"
    "h2{font-size:.8rem;text-transform:uppercase;letter-spacing:.08em;color:var(--dim);margin-bottom:.75rem}\n"
    ".kv{display:flex;gap:.75rem;padding:.2rem 0}\n"
    ".kv span{color:var(--dim);min-width:9rem}\n"
    ".kv.ctx b{color:var(--acc)}\n"
    ".bar{background:var(--bg);border:1px solid var(--line);border-radius:4px;height:14px;overflow:hidden;margin:.25rem 0}\n"
    ".bar i{display:block;height:100%;background:var(--acc);width:0;transition:width .5s}\n"
    ".bar.warm i{background:var(--warm)}\n"
    ".slot{padding:.4rem 0;border-top:1px solid var(--line)}\n"
    ".slot:first-child{border-top:0}\n"
    ".slot .lbl{display:flex;justify-content:space-between;font-size:.85rem}\n"
    ".slot .lbl .st{color:var(--dim)}\n"
    ".slot .st.decode{color:var(--ok)}\n"
    ".slot .st.prefill{color:var(--acc)}\n"
    ".badge{display:inline-block;padding:0 .45em;border-radius:4px;font-style:normal;font-size:.72rem;text-transform:uppercase;letter-spacing:.05em;border:1px solid var(--line);color:var(--dim)}\n"
    ".badge.interactive{color:var(--ok);border-color:var(--ok)}\n"
    ".badge.batch{color:var(--warm);border-color:var(--warm)}\n"
    ".note{color:var(--warm);font-size:.85rem;margin-top:.4rem}\n"
    ".ev{color:var(--dim);font-size:.85rem;margin-top:.4rem}\n"
    "pre{background:var(--bg);border:1px solid var(--line);border-radius:6px;padding:.75rem;overflow-x:auto;font-size:.82rem;margin:.5rem 0}\n"
    "footer{color:var(--dim);font-size:.8rem;margin-top:1.5rem}\n"
    "noscript p{color:var(--dim)}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<h1>ds4 console<small>accretion v0</small></h1>\n"
    "<section id=\"status\">\n"
    "<h2>Status</h2>\n"
    "\n";

static const char ds4_console_html_tail[] =
    "<div id=\"status-extra\"></div>\n"
    "</section>\n"
    "<section id=\"activity\">\n"
    "<h2>Activity</h2>\n"
    "<noscript><p>Enable JavaScript for the live activity view. The STATUS and CONNECT sections work without it.</p></noscript>\n"
    "<div id=\"slots\"></div>\n"
    "<div id=\"cache\"></div>\n"
    "<div id=\"events\" class=\"ev\"></div>\n"
    "</section>\n"
    "<section id=\"routing\">\n"
    "<h2>Routing</h2>\n"
    "<noscript><p>Enable JavaScript for routing telemetry.</p></noscript>\n"
    "<div id=\"rt-summary\" class=\"ev\"></div>\n"
    "<div id=\"rt-layers\"></div>\n"
    "<div id=\"rt-top\"></div>\n"
    "<div id=\"rt-advisor\"></div>\n"
    "</section>\n"
    "<section id=\"models\">\n"
    "<h2>Models</h2>\n"
    "<noscript><p>Enable JavaScript for the model picker. GET /v1/models/available works without it.</p></noscript>\n"
    "<div id=\"mdl-list\"></div>\n"
    "<div id=\"mdl-note\" class=\"ev\"></div>\n"
    "<div class=\"ev\">interactive: resident, fast decode &middot; batch: streamed, big-model capability. t/s figures are recorded references, not live measurements.</div>\n"
    "<div class=\"ev\">Prepare a new model from the command line for now: <code>accretion-prepare &lt;source.gguf&gt;</code>. Download-from-console arrives after v0.1.</div>\n"
    "</section>\n"
    "<section id=\"connect\">\n"
    "<h2>Connect</h2>\n"
    "<p>claude CLI:</p>\n"
    "<pre id=\"cc\">ANTHROPIC_BASE_URL=http://&lt;host&gt;:8000 \\\n"
    "ANTHROPIC_MODEL=deepseek-v4-flash \\\n"
    "ANTHROPIC_SMALL_FAST_MODEL=deepseek-v4-flash \\\n"
    "claude</pre>\n"
    "<p>OpenAI-compatible clients:</p>\n"
    "<pre id=\"oc\">base_url = \"http://&lt;host&gt;:8000/v1\"\n"
    "model    = \"deepseek-v4-flash\"</pre>\n"
    "</section>\n"
    "<footer>Model switching requires an admin token; everything else is read-only. Prepare-pipeline UX arrives post-v0.1.</footer>\n"
    "<script>\n"
    "(function(){\n"
    "\"use strict\";\n"
    "var host = window.location.host || \"<host>:8000\";\n"
    "function fill(id){var e=document.getElementById(id);e.textContent=e.textContent.replace(/<host>:8000/g,host);}\n"
    "fill(\"cc\");fill(\"oc\");\n"
    "function gb(n){return (n/1073741824).toFixed(2)+\" GiB\";}\n"
    "fetch(\"/v1/capabilities\").then(function(r){return r.json();}).then(function(c){\n"
    "  var x=document.getElementById(\"status-extra\"),h=\"\";\n"
    "  if(c.throughput){h+='<div class=\"kv\"><span>throughput ref</span><b>'+\n"
    "    Object.keys(c.throughput).map(function(k){return k+\": \"+c.throughput[k];}).join(\" &middot; \")+\"</b></div>\";}\n"
    "  var ec=c.serving&&c.serving.expert_cache;\n"
    "  if(ec&&ec.budget_bytes){h+='<div class=\"kv\"><span>expert cache</span><b>'+gb(ec.budget_bytes)+\" budget</b></div>\";}\n"
    "  var dio=c.serving&&c.serving.direct_io;\n"
    "  if(dio&&dio.state){var warn=dio.state!==\"engaged\";\n"
    "    h+='<div class=\"kv\"><span>direct I/O</span><b'+(warn?' style=\"color:#c33\"':'')+'>'+dio.state+\n"
    "      (warn&&dio.disable_errno?\" (errno \"+dio.disable_errno+\")\":\"\")+\"</b></div>\";}\n"
    "  x.innerHTML=h;\n"
    "}).catch(function(){});\n"
    "var lastRestores=-1;\n"
    "function poll(){\n"
    "  fetch(\"/v1/activity\").then(function(r){return r.json();}).then(function(a){\n"
    "    var h=\"\";\n"
    "    a.slots.forEach(function(s){\n"
    "      h+='<div class=\"slot\"><div class=\"lbl\"><span>slot '+s.id+'</span><span class=\"st '+s.state+'\">';\n"
    "      if(s.state===\"prefill\"&&s.prefill){\n"
    "        var p=s.prefill,pct=p.tokens_total>0?100*p.tokens_done/p.tokens_total:0;\n"
    "        h+=\"prefill \"+p.tokens_done+\"/\"+p.tokens_total+\" &middot; \"+p.tokens_per_second.toFixed(1)+\" t/s\";\n"
    "        if(p.eta_seconds!==undefined){h+=\" &middot; ETA \"+p.eta_seconds.toFixed(0)+\"s\";}\n"
    "        h+='</span></div><div class=\"bar\"><i style=\"width:'+pct.toFixed(1)+'%\"></i></div>';\n"
    "      }else if(s.state===\"decode\"){\n"
    "        h+=\"decoding &middot; \"+s.generated_tokens+\" tokens</span></div>\";\n"
    "      }else{h+=\"idle</span></div>\";}\n"
    "      h+=\"</div>\";\n"
    "    });\n"
    "    document.getElementById(\"slots\").innerHTML=h;\n"
    "    var ec=a.expert_cache,ch=\"\";\n"
    "    if(ec&&ec.budget_bytes&&ec.counted_bytes!==undefined){\n"
    "      var w=100*ec.counted_bytes/ec.budget_bytes;\n"
    "      ch='<div class=\"lbl kv\"><span>expert cache warmth</span><b>'+gb(ec.counted_bytes)+\" / \"+gb(ec.budget_bytes)+\n"
    "         \" (\"+w.toFixed(0)+\"%, \"+ec.entries+' entries)</b></div><div class=\"bar warm\"><i style=\"width:'+\n"
    "         Math.min(w,100).toFixed(1)+'%\"></i></div>';\n"
    "      if(w<90){ch+='<div class=\"note\">first sessions are slower until the cache warms</div>';}\n"
    "    }\n"
    "    document.getElementById(\"cache\").innerHTML=ch;\n"
    "    var kv=a.kv_events,eh=\"\";\n"
    "    if(kv){\n"
    "      eh=\"anchors stored \"+kv.stores+\" &middot; restored \"+kv.restores+\" (this uptime)\";\n"
    "      if(lastRestores>=0&&kv.restores>lastRestores&&kv.last_restore_tokens>0){\n"
    "        eh+=\"<br>restored \"+kv.last_restore_tokens+\" tokens in \"+kv.last_restore_ms.toFixed(0)+\" ms\";\n"
    "      }\n"
    "      lastRestores=kv.restores;\n"
    "    }\n"
    "    document.getElementById(\"events\").innerHTML=eh;\n"
    "  }).catch(function(){});\n"
    "}\n"
    "function pollRouting(){\n"
    "  fetch(\"/v1/routing-stats\").then(function(r){return r.json();}).then(function(rs){\n"
    "    if(!rs.enabled||!rs.totals||!rs.totals.selections){\n"
    "      document.getElementById(\"rt-summary\").textContent=\"routing counters \"+(rs.enabled?\"warming (no selections yet)\":\"disabled\");return;}\n"
    "    var t=rs.totals;\n"
    "    document.getElementById(\"rt-summary\").innerHTML=\n"
    "      t.selections.toLocaleString()+\" selections &middot; \"+t.distinct_keys+\" (layer,expert) keys &middot; \"+\n"
    "      \"LRU hit rate \"+(100*t.hit_rate).toFixed(1)+\"% &middot; decode \"+t.decode_tokens.toLocaleString()+\n"
    "      \" t / prefill \"+t.prefill_tokens.toLocaleString()+\" t\";\n"
    "    var h='<div class=\"kv\"><span>per-layer entropy</span><b>selection-distribution entropy / max</b></div>';\n"
    "    rs.per_layer.forEach(function(L){\n"
    "      var pct=L.entropy_max_nats>0?100*L.selection_entropy_nats/L.entropy_max_nats:0;\n"
    "      h+='<div class=\"lbl kv\" style=\"font-size:.75rem;padding:0\"><span>L'+L.layer+'</span>'+\n"
    "         '<b style=\"flex:1\"><i style=\"display:inline-block;height:8px;background:var(--acc);width:'+pct.toFixed(0)+'%\"></i> '+\n"
    "         L.selection_entropy_nats.toFixed(2)+'</b></div>';\n"
    "    });\n"
    "    document.getElementById(\"rt-layers\").innerHTML=h;\n"
    "    var th='<div class=\"kv\" style=\"margin-top:.5rem\"><span>hottest experts</span><b>selections (share, hit rate)</b></div>';\n"
    "    rs.top_experts.slice(0,10).forEach(function(e){\n"
    "      th+='<div class=\"kv\" style=\"font-size:.8rem;padding:0\"><span>L'+e.layer+' E'+e.expert+'</span><b>'+\n"
    "          e.selections.toLocaleString()+' ('+(100*e.share).toFixed(2)+'%, '+(100*e.hit_rate).toFixed(0)+'% hit)</b></div>';\n"
    "    });\n"
    "    document.getElementById(\"rt-top\").innerHTML=th;\n"
    "    var ah=\"\";\n"
    "    if(rs.advisor&&rs.advisor.budgets){\n"
    "      ah='<div class=\"kv\" style=\"margin-top:.5rem\"><span>cache advisor</span><b>estimated hit rate if cache held top-K experts (static skew)</b></div>';\n"
    "      rs.advisor.budgets.forEach(function(a){\n"
    "        ah+='<div class=\"kv\" style=\"font-size:.8rem;padding:0\"><span>'+a.budget_gib.toFixed(1)+' GiB</span><b>'+\n"
    "            a.cache_experts+' experts &rarr; '+(100*a.estimated_hit_rate_static).toFixed(1)+'%</b></div>';\n"
    "      });\n"
    "    }\n"
    "    document.getElementById(\"rt-advisor\").innerHTML=ah;\n"
    "  }).catch(function(){});\n"
    "}\n"
    "function esc(t){var d=document.createElement(\"i\");d.textContent=t;return d.innerHTML;}\n"
    "function adminToken(){return localStorage.getItem(\"accretionAdminToken\")||\"\";}\n"
    "function askToken(){var t=window.prompt(\"Admin token (ACCRETION_ADMIN_TOKEN)\",adminToken());\n"
    "  if(t!==null){localStorage.setItem(\"accretionAdminToken\",t);}return adminToken();}\n"
    "function selectModel(path){\n"
    "  var t=adminToken()||askToken();if(!t){return;}\n"
    "  fetch(\"/v1/models/select\",{method:\"POST\",headers:{\"Authorization\":\"Bearer \"+t,\n"
    "    \"Content-Type\":\"application/json\"},body:JSON.stringify({path:path})})\n"
    "  .then(function(r){return r.json().then(function(j){return {st:r.status,j:j};});})\n"
    "  .then(function(x){var n=document.getElementById(\"mdl-note\");\n"
    "    if(x.st===200){n.textContent=\"swapping: server is draining and restarting on \"+path+\" — this page will recover when it is back\";}\n"
    "    else if(x.st===401){localStorage.removeItem(\"accretionAdminToken\");n.textContent=\"wrong admin token\";}\n"
    "    else{n.textContent=(x.j&&x.j.error&&x.j.error.message)||(\"select failed (HTTP \"+x.st+\")\");}\n"
    "  }).catch(function(){document.getElementById(\"mdl-note\").textContent=\"select request failed\";});\n"
    "}\n"
    "function pollModels(){\n"
    "  fetch(\"/v1/models/available\").then(function(r){return r.json();}).then(function(mv){\n"
    "    var h=\"\";\n"
    "    mv.models.forEach(function(m){\n"
    "      var md=m.mode||\"unknown\";\n"
    "      var badge='<i class=\"badge '+esc(md)+'\" title=\"'+esc(m.mode_reason||\"\")+'\">'+esc(md)+\"</i>\";\n"
    "      h+='<div class=\"kv\"><span>'+esc(m.name)+(m.active?' <b style=\"color:var(--ok)\">[active]</b>':'')+'</span><b>'+\n"
    "         badge+(m.decode_tps_reference?\" \"+m.decode_tps_reference+\" t/s ref\":\"\")+\" &middot; \"+\n"
    "         gb(m.size_bytes)+\" &middot; \"+esc(m.quant)+\" &middot; \"+esc(m.architecture)+\n"
    "         (m.loadable===\"no\"?\" &middot; not loadable\":m.loadable===\"unknown\"?\" &middot; loadable?\":\"\")+\n"
    "         (mv.select_enabled&&!m.active&&m.loadable!==\"no\"?\n"
    "          ' <button onclick=\"accretionSelect(&quot;'+esc(m.path)+'&quot;)\">switch</button>':\"\")+\n"
    "         \"</b></div>\";\n"
    "    });\n"
    "    document.getElementById(\"mdl-list\").innerHTML=h;\n"
    "    if(!mv.select_enabled){document.getElementById(\"mdl-note\").textContent=\n"
    "      \"read-only: set ACCRETION_ADMIN_TOKEN in the server environment to enable switching\";}\n"
    "  }).catch(function(){});\n"
    "}\n"
    "window.accretionSelect=selectModel;\n"
    "pollModels();setInterval(pollModels,15000);\n"
    "poll();setInterval(poll,2500);\n"
    "pollRouting();setInterval(pollRouting,10000);\n"
    "})();\n"
    "</script>\n"
    "</body>\n"
    "</html>\n"
    "\n";

#endif /* DS4_CONSOLE_H */
